// @ts-check

/** @typedef {import('../contracts/systemManifest').AgentCapabilityDescriptor} AgentCapabilityDescriptor */

const objectResultSchema = {
  type: /** @type {const} */ ('object'),
  additionalProperties: false,
  required: ['changed'],
  properties: {
    changed: { type: 'boolean' },
    reason: { type: ['string', 'null'] },
  },
};

/**
 * Keep command cards mechanically uniform. Domain-specific truth remains in
 * each explicit handler and verifier rather than in this construction helper.
 *
 * @param {{
 *   id: string,
 *   title: string,
 *   ownerDomainId: AgentCapabilityDescriptor['ownerDomainId'],
 *   risk: AgentCapabilityDescriptor['risk'],
 *   targetKinds: AgentCapabilityDescriptor['targetKinds'],
 *   required: string[],
 *   properties: Record<string, Readonly<Record<string, unknown>>>,
 *   reads: string[],
 *   writes: string[],
 *   sideEffects: string[],
 *   verifier: string,
 *   sourcePath: string,
 *   sourceSymbol: string,
 * }} options
 * @returns {AgentCapabilityDescriptor}
 */
function capability(options) {
  return {
    id: options.id,
    uri: `millos://capability/${options.id}`,
    version: 1,
    status: 'implemented',
    title: options.title,
    ownerDomainId: options.ownerDomainId,
    modes: ['simulation', 'shadow'],
    risk: options.risk,
    targetKinds: options.targetKinds,
    parameters: {
      type: 'object',
      additionalProperties: false,
      required: options.required,
      properties: options.properties,
    },
    result: objectResultSchema,
    reads: options.reads,
    writes: options.writes,
    preconditions: [
      'Target exists in the canonical owner domain.',
      'Observed owner-domain revision is current.',
      'Actor holds a scoped grant for the active mode and target.',
    ],
    invariantIds: ['INV.AUTHORITY.DEFAULT_DENY', 'INV.TRUTH.MODE_LABEL', 'INV.RESOURCE.BOUNDED'],
    sideEffects: options.sideEffects,
    reversible: false,
    compensationCapability: null,
    supportsPreview: true,
    expectedLatencyMs: 15,
    costModel: {
      latencyClass: 'local',
      computeClass: 'trivial',
      externalCalls: false,
      boundedCollectionWrites: 1,
    },
    verifier: options.verifier,
    currentCallers: [],
    sourceRefs: [
      {
        kind: 'source',
        path: options.sourcePath,
        symbol: options.sourceSymbol,
        evidenceLevel: 'source',
      },
      {
        kind: 'runtime',
        path: 'src/agent/adapters/runtime/runtimeCommandHandlers.ts',
        symbol: options.id,
        evidenceLevel: 'runtime',
      },
    ],
  };
}

/** @type {AgentCapabilityDescriptor[]} */
export const COMMAND_CAPABILITY_DESCRIPTORS = [
  capability({
    id: 'ai.respond-to-decision',
    title: 'Respond to an AI decision',
    ownerDomainId: 'production',
    risk: 'medium',
    targetKinds: ['decision'],
    required: ['decisionUri', 'disposition'],
    properties: {
      decisionUri: { type: 'string', pattern: '^millos://decision/' },
      disposition: { type: 'string', enum: ['accepted', 'modified', 'rejected', 'deferred'] },
      note: { type: 'string' },
      modifiedAction: { type: 'string' },
    },
    reads: ['production.aiDecisions[]'],
    writes: ['production.aiDecisions[].response', 'production.aiDecisions[].status'],
    sideEffects: ['Records a bounded response to the recommendation.'],
    verifier:
      'The target decision records the requested disposition and a current response timestamp.',
    sourcePath: 'src/stores/productionStore.ts',
    sourceSymbol: 'recordDecisionResponse',
  }),
  capability({
    id: 'maintenance.request-repair',
    title: 'Request repair work',
    ownerDomainId: 'maintenance',
    risk: 'medium',
    targetKinds: ['breakdown'],
    required: ['breakdownUri'],
    properties: { breakdownUri: { type: 'string', pattern: '^millos://breakdown/' } },
    reads: [
      'maintenance.activeBreakdowns[]',
      'maintenance.workOrders[]',
      'maintenance.partsInventory',
    ],
    writes: ['maintenance.workOrders[].phase', 'maintenance.partsInventory'],
    sideEffects: ['Consumes required simulated parts when repair begins.'],
    verifier: 'The work order enters repairing or returns an explicit non-mutating block reason.',
    sourcePath: 'src/stores/breakdownStore.ts',
    sourceSymbol: 'startRepair',
  }),
  capability({
    id: 'maintenance.request-restart',
    title: 'Request controlled machine restart',
    ownerDomainId: 'maintenance',
    risk: 'high',
    targetKinds: ['breakdown'],
    required: ['breakdownUri'],
    properties: { breakdownUri: { type: 'string', pattern: '^millos://breakdown/' } },
    reads: ['maintenance.workOrders[]'],
    writes: ['maintenance.workOrders[].phase', 'maintenance.workOrders[].audit'],
    sideEffects: ['Queues the far-side central tick restart confirmation.'],
    verifier: 'Only a verified repair enters restart_requested.',
    sourcePath: 'src/stores/breakdownStore.ts',
    sourceSymbol: 'requestMachineRestart',
  }),
  capability({
    id: 'quality.hold-batch',
    title: 'Place a product batch on quality hold',
    ownerDomainId: 'material',
    risk: 'medium',
    targetKinds: ['batch'],
    required: ['batchUri', 'reason'],
    properties: {
      batchUri: { type: 'string', pattern: '^millos://batch/' },
      reason: { type: 'string' },
    },
    reads: ['material.productionBatches[]'],
    writes: [
      'material.productionBatches[].disposition',
      'material.productionBatches[].dispositionReason',
    ],
    sideEffects: ['The quality dispatch interlock excludes the held batch.'],
    verifier: 'The exact unshipped batch is held with the supplied reason.',
    sourcePath: 'src/stores/materialFlowStore.ts',
    sourceSymbol: 'setBatchDisposition',
  }),
  capability({
    id: 'quality.release-batch',
    title: 'Release a held product batch',
    ownerDomainId: 'material',
    risk: 'high',
    targetKinds: ['batch'],
    required: ['batchUri', 'reason'],
    properties: {
      batchUri: { type: 'string', pattern: '^millos://batch/' },
      reason: { type: 'string' },
    },
    reads: ['material.productionBatches[]', 'quality.contaminationAlerts[]'],
    writes: [
      'material.productionBatches[].disposition',
      'material.productionBatches[].dispositionReason',
    ],
    sideEffects: ['Released mass may become dispatchable after all quality interlocks pass.'],
    verifier: 'A held batch becomes released while recalled or shipped product remains unchanged.',
    sourcePath: 'src/stores/materialFlowStore.ts',
    sourceSymbol: 'setBatchDisposition',
  }),
  capability({
    id: 'dispatch.release',
    title: 'Release the shipping transfer',
    ownerDomainId: 'logistics',
    risk: 'high',
    targetKinds: ['dispatch'],
    required: ['dispatchUri'],
    properties: { dispatchUri: { type: 'string', pattern: '^millos://dispatch/' } },
    reads: ['logistics.shipping', 'quality.dispatchReleased', 'material.productionBatches[]'],
    writes: ['logistics.shipping.transferReady'],
    sideEffects: ['Allows the current simulated shipping load sequence to proceed.'],
    verifier:
      'Transfer readiness changes only for a docked shipping truck with current quality release.',
    sourcePath: 'src/stores/truckScheduleStore.ts',
    sourceSymbol: 'setTruckTransferReady',
  }),
  capability({
    id: 'simulation.set-speed',
    title: 'Set deterministic simulation speed',
    ownerDomainId: 'simulation',
    risk: 'medium',
    targetKinds: ['simulation'],
    required: ['simulationUri', 'speed'],
    properties: {
      simulationUri: { type: 'string', pattern: '^millos://simulation/' },
      speed: { type: 'number', minimum: 0, maximum: 10800 },
    },
    reads: ['simulation.gameSpeed'],
    writes: ['simulation.gameSpeed'],
    sideEffects: ['Changes future simulated-time advancement while preserving wall time.'],
    verifier: 'The sanitized game speed equals the requested value.',
    sourcePath: 'src/stores/gameSimulationStore.ts',
    sourceSymbol: 'setGameSpeed',
  }),
  capability({
    id: 'simulation.start-fire-drill',
    title: 'Start a simulated fire drill',
    ownerDomainId: 'simulation',
    risk: 'high',
    targetKinds: ['simulation'],
    required: ['simulationUri'],
    properties: {
      simulationUri: { type: 'string', pattern: '^millos://simulation/' },
      totalZones: { type: 'integer', minimum: 0, maximum: 16 },
    },
    reads: ['simulation.emergencyActive', 'simulation.crisis'],
    writes: [
      'simulation.emergencyDrillMode',
      'simulation.drillMetrics',
      'simulation.safetyEvents[]',
    ],
    sideEffects: ['Stops simulated equipment and starts the egress verification sequence.'],
    verifier: 'The drill interlock and metrics become active only from a non-emergency state.',
    sourcePath: 'src/stores/gameSimulationStore.ts',
    sourceSymbol: 'startEmergencyDrill',
  }),
  capability({
    id: 'scada.acknowledge-alarm',
    title: 'Acknowledge a simulated SCADA alarm',
    ownerDomainId: 'scada',
    risk: 'low',
    targetKinds: ['alarm'],
    required: ['alarmUri'],
    properties: {
      alarmUri: { type: 'string', pattern: '^millos://alarm/' },
      note: { type: 'string' },
    },
    reads: ['scada.activeAlarms[]'],
    writes: ['scada.activeAlarms[].acknowledged'],
    sideEffects: ['Records acknowledgement while preserving the alarm condition.'],
    verifier: 'The exact active alarm records acknowledgement.',
    sourcePath: 'src/scada/SCADAService.ts',
    sourceSymbol: 'acknowledgeAlarm',
  }),
  capability({
    id: 'scada.write-setpoint',
    title: 'Write a simulated SCADA setpoint',
    ownerDomainId: 'scada',
    risk: 'critical',
    targetKinds: ['tag'],
    required: ['tagUri', 'value'],
    properties: {
      tagUri: { type: 'string', pattern: '^millos://tag/' },
      value: { type: 'number' },
    },
    reads: ['scada.mode', 'scada.connection', 'scada.tags[]'],
    writes: ['scada.tags[].value'],
    sideEffects: ['Writes only through the local SimulationAdapter or shadow evaluator.'],
    verifier:
      'The simulated writable tag reads back the requested value with explicit mode evidence.',
    sourcePath: 'src/scada/SCADAService.ts',
    sourceSymbol: 'writeSetpoint',
  }),
];
